### ISSUE TITLE
Baby Error Log Request

### ISSUE THREAD

**Issue by Pillowkitty** [feldoh/EasyIdeoSwitching#1]
RimWorld 1.5.4184 rev404
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
RimWorld.VersionControl:LogVersionNumber ()
Verse.Root:CheckGlobalInit ()
Verse.Root:Start ()
Verse.Root_Entry:Start ()

Initializing new game with mods:
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - Ludeon.RimWorld.Ideology
  - Ludeon.RimWorld.Biotech
  - Taggerung.EasyIdeoSwitching
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
Verse.Game:InitNewGame ()
Verse.Root_Play/<>c:<Start>b__1_2 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__28_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

Exception processing alert RimWorld.Alert_DateRitualComing: System.NullReferenceException: Object reference not set to an instance of an object
[Ref EEE40279]
 at RimWorld.Alert_DateRitualComing.UpcomingRituals () [0x0002b] in <2464551dcee346df9bf15b1c06ef09e9>:0 
 at RimWorld.Alert_DateRitualComing.GetReport () [0x00000] in <2464551dcee346df9bf15b1c06ef09e9>:0 
 at RimWorld.Alert.Recalculate () [0x00012] in <2464551dcee346df9bf15b1c06ef09e9>:0 
 at RimWorld.AlertsReadout.CheckAddOrRemoveAlert (RimWorld.Alert alert, System.Boolean forceRemove) [0x00000] in <2464551dcee346df9bf15b1c06ef09e9>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.Log:ErrorOnce (string,int)
RimWorld.AlertsReadout:CheckAddOrRemoveAlert (RimWorld.Alert,bool)
RimWorld.AlertsReadout:AlertsReadoutUpdate ()
RimWorld.UIRoot_Play:UIRootUpdate ()
Verse.Root:Update ()
Verse.Root_Play:Update ()

Exception in UIRootUpdate: System.NullReferenceException: Object reference not set to an instance of an object
[Ref 2E9CF995]
 at RimWorld.AlertsReadout.AlertsReadoutUpdate () [0x001dc] in <2464551dcee346df9bf15b1c06ef09e9>:0 
 at RimWorld.UIRoot_Play.UIRootUpdate () [0x00020] in <2464551dcee346df9bf15b1c06ef09e9>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
RimWorld.UIRoot_Play:UIRootUpdate ()
Verse.Root:Update ()
Verse.Root_Play:Update ()

Exception in UIRootUpdate: System.NullReferenceException: Object reference not set to an instance of an object
[Ref 2E9CF995] Duplicate stacktrace, see ref for original
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
RimWorld.UIRoot_Play:UIRootUpdate ()
Verse.Root:Update ()
Verse.Root_Play:Update ()

**Comment by Pillowkitty** [comment]
![20240911171218_1](https://github.com/user-attachments/assets/1e3be9d4-9a67-4723-ba1c-25ed6ee51c00)

**Comment by feldoh** [comment]
Do you definitely have the latest version of Rimworld and the Ideology DLC because I'm looking at the core Rimworld game code here and I'm more or less sure this is actually impossible if you're up to date. The null is coming from 
`at RimWorld.Alert_DateRitualComing.UpcomingRituals () [0x0002b]`
in the current version of the game that equates to:
```csharp
 private void UpcomingRituals()
    {
      this.ritualEntries.Clear();
      foreach (Ideo allIdeo in Faction.OfPlayer.ideos.AllIdeos)
      {
        foreach (Precept_Ritual preceptRitual in allIdeo.PreceptsListForReading.OfType<Precept_Ritual>())
        {
          ...
        }
      }
    }
```
specifically `allIdeo.PreceptsListForReading`
the game doesn't check this for null because it can never be null. You'd have to have a null ideology in your list of faction ideologies, all this mod does is .setPrimary with the ideo it's given, which can't be null and if it was would cause a different error. I'm at a total loss and still can't replicate it.

The only thing I can think of is to fail fast and not let you swap ideo if it's somehow null so you can try this and see if it helps, let me know if it does.
[EasyIdeoSwitching.zip](https://github.com/user-attachments/files/16971196/EasyIdeoSwitching.zip)

If that doesn't work I suggest completely clearing your Rimworld installation, remove all mods, all configs etc and see if that helps because I have no idea how you're getting null ideologies, this mod as far as I can tell simply cannot cause this issue. So either you have an outdated version (in which case the code I've analysed might not match) or your version is corrupt in some way, or there's another mod causing issues that's somehow loaded.

**Comment by Pillowkitty** [comment]
![20240911180943_1](https://github.com/user-attachments/assets/d49bc3e1-2ccd-4b06-917d-229fc5473f54)
![20240911181112_1](https://github.com/user-attachments/assets/d19074c0-5b04-44c3-99ec-a0cc8de403de)
Don't quite understand all the lingo but the zip you provided looks to work just fine. I can try backing up my LocalLow and doing an entire reinstall of the game then attempt the steam version again. So very odd indeed.

**Comment by feldoh** [comment]
How strange, well I'll push the new version, I don't think there's anything that recompiling should have done.

**Comment by Pillowkitty** [comment]
Thanks for hearing me out, I'll go boot up the old mega modded save and see how that performs with the new version!
